repos:

- repo: local
  hooks:
  - id: black
    name: black
    entry: pipenv run black
    args: [--quiet]
    language: system
    types: [python]
  
  - id: mypy
    name: mypy
    exclude: (?x)^(
        (.*)/setup.py
      )$
    entry: pipenv run mypy
    args: ["--namespace-packages", "-p", "apd.sensors"]
    language: system
    pass_filenames: false
    types: [python]

  - id: flake8
    name: flake8
    entry: pipenv run flake8
    language: system
    types: [python]
