# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: APD Sensors

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 . --count --show-source --statistics
    - name: Lint with black
      run: |
        pipenv run black --check
    - name: Lint with mypy
      run: |
        pipenv run mypy --namespace-packages -p apd.sensors
    - name: Test with pytest
      run: |
        pipenv run pytest
